version: "3.8"
services:
  db:
    image: postgres:15.1
    container_name: db_bookingalien
    restart: always
    expose:
      - '5432:5432'
    environment:
        POSTGRES_PASSWORD: 'admin'
        POSTGRES_USER: 'admin'
    volumes:
      - db-data:/var/lib/postgres
    networks:
      - dev
  app:
    build: docker/php
    container_name: app_bookingalien
    ports:
      - "8080:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
networks:
  dev:
volumes:
  db-data: